In [1]:
%load_ext watermark

In [2]:
import os
import subprocess

os.environ["POLARS_FORCE_NEW_STREAMING"] = "1"

import pandas as pd
import polars as pl
from tqdm import tqdm

from pylib._seed_global_rngs import seed_global_rngs

Covasim 3.1.6 (2024-01-28) — © 2020-2024 by IDM

In [3]:
pd.options.display.float_format = "{:,.1f}".format

In [4]:
%watermark -diwmuv -iv

Last updated: 2026-09-20T02:10:01.690835+00:00

Python implementation: CPython
Python version       : 3.10.12
IPython version      : 7.31.1

Compiler    : GCC 11.4.0
OS          : Linux
Release     : 6.8.0-1064-azure
Machine     : x86_64
Processor   : x86_64
CPU cores   : 4
Architecture: 64bit

pandas: 2.2.3
polars: 1.29.0

Watermark: 2.4.3

In [5]:
teeplot_subdir = "2025-05-30-compscreen-mutcount"
teeplot_subdir

'2025-05-30-compscreen-mutcount'

In [6]:
seed_global_rngs(1)

## Get Data

In [7]:
data_sources = {
    "uk": "https://osf.io/mkjy5/download",
    "multistrain": "https://osf.io/ywmpt/download",
    "vanilla": "https://osf.io/r8skg/download",
    "vanilla-big": "https://osf.io/j4795/download",
    "vanilla-big-1.3x": "https://osf.io/cnp5z/download",
}
tmp_path = f"/tmp/{teeplot_subdir}.pqt"

In [8]:
results = []

for source_name, url in data_sources.items():
    print(f"Downloading {source_name} data from {url}")

    subprocess.run(
        [
            "wget",
            "--tries=5",
            "--show-progress",
            "--progress=bar:force",
            "-O",
            str(tmp_path),
            url,
        ],
        check=True,
    )
    print("done!")

    df = pl.scan_parquet(
        tmp_path,
        low_memory=True,
        retries=5,
    )

    unique_groups = (
        df.unique(
            [
                "trt_name",
                "trt_n_downsample",
                "trt_hsurf_bits",
                "replicate_uuid",
            ]
        )
        .select(
            pl.col("trt_name"),
            pl.col("trt_n_downsample"),
            pl.col("trt_hsurf_bits"),
            pl.col("replicate_uuid"),
        )
        .drop_nans()
        .drop_nulls()
        .collect(engine="streaming")
    )

    for (trt_name, trt_n_downsample, trt_hsurf_bits, replicate_uuid) in tqdm(
        [*unique_groups.iter_rows()],
    ):
        group = df.filter(
            (pl.col("trt_name") == trt_name)
            & (pl.col("trt_n_downsample") == trt_n_downsample)
            & (pl.col("trt_hsurf_bits") == trt_hsurf_bits)
            & (pl.col("replicate_uuid") == replicate_uuid)
        ).collect(engine="streaming")

        group_df = group.to_pandas()
        res = [
            {
                "sum leaf count": group_df.loc[
                    group_df["is_focal_defmut"],
                    "num_leaves",
                ].sum(),
                "sum defmut": group_df["is_focal_defmut"].astype(bool).sum(),
            },
        ]
        results.extend(
            {
                "source_name": source_name,
                "trt_name": trt_name,
                "trt_n_downsample": trt_n_downsample,
                "trt_hsurf_bits": trt_hsurf_bits,
                "replicate_uuid": replicate_uuid,
                **record,
            }
            for record in res
        )

Downloading uk data from https://osf.io/mkjy5/download

--2026-09-20 02:10:01--  https://osf.io/mkjy5/download
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osf.io/download/mkjy5 [following]
--2026-09-20 02:10:02--  https://osf.io/download/mkjy5
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 308 Permanent Redirect
Location: https://osf.io/download/mkjy5/ [following]
--2026-09-20 02:10:02--  https://osf.io/download/mkjy5/
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 302 Found
Location: https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682c8b8ca9789d8b628f3f38 [following]
--2026-09-20 02:10:02--  https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682c8b8ca9789d8b628f3f38
Resolving files.osf.io (files.osf.io)... 35.186.214.196
Connecting to files.osf.io (files.osf.io)|35.186.214.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-us-east1/287d491af51f17bc5f99c562c1317362a49cd5cc49427ab35d08356a2a557cf0?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-uk-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-uk-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870263&Signature=izTDwd0XzqItgvLrc%2FDhGeMtzV8WLYLOB8INE58OYzpI9WEWGZSlgite3P9JhIoQU9aa1qVeLHirv2Tuuryfw2WeXzNwnMCi3ELgNGUWlflqXhfTD1hvd6AuMN45%2BTNG8pa%2FGb4FReau1GKXTvSbgSZtkfADHR3l3Nk%2BBGbuQvHgep%2BXJrbTsO8%2B8mFSsEFATXtF10bAeTcXQay8LeUFQdp6j6V7Qg9CQxH7t5tnLUCVQytKV4WWYz2k8oKT6vh928a1jHZBJbRz2YMUGeMRqU06kZ9t6yN0rkSsBn5b3y%2BhibE%2FbEipQQ2RaRuK3FxlMWtxTH6qpUSGYx4dZvN29w%3D%3D [following]
--2026-09-20 02:10:03--  https://storage.googleapis.com/cos-osf-prod-files-us-east1/287d491af51f17bc5f99c562c1317362a49cd5cc49427ab35d08356a2a557cf0?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-uk-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-uk-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870263&Signature=izTDwd0XzqItgvLrc%2FDhGeMtzV8WLYLOB8INE58OYzpI9WEWGZSlgite3P9JhIoQU9aa1qVeLHirv2Tuuryfw2WeXzNwnMCi3ELgNGUWlflqXhfTD1hvd6AuMN45%2BTNG8pa%2FGb4FReau1GKXTvSbgSZtkfADHR3l3Nk%2BBGbuQvHgep%2BXJrbTsO8%2B8mFSsEFATXtF10bAeTcXQay8LeUFQdp6j6V7Qg9CQxH7t5tnLUCVQytKV4WWYz2k8oKT6vh928a1jHZBJbRz2YMUGeMRqU06kZ9t6yN0rkSsBn5b3y%2BhibE%2FbEipQQ2RaRuK3FxlMWtxTH6qpUSGYx4dZvN29w%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 64.233.180.207, 172.253.115.207, 172.253.122.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|64.233.180.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 201771388 (192M) [application/octet-stream]
Saving to: ‘/tmp/2025-05-30-compscreen-mutcount.pqt’

/tmp/2025-05-30-com 100%[===================>] 192.42M   206MB/s    in 0.9s

2026-09-20 02:10:05 (206 MB/s) - ‘/tmp/2025-05-30-compscreen-mutcount.pqt’ saved [201771388/201771388]

done!

100%|██████████| 70/70 [00:28<00:00,  2.46it/s]
--2026-09-20 02:10:33--  https://osf.io/ywmpt/download
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osf.io/download/ywmpt [following]
--2026-09-20 02:10:33--  https://osf.io/download/ywmpt
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 308 Permanent Redirect
Location: https://osf.io/download/ywmpt/ [following]
--2026-09-20 02:10:33--  https://osf.io/download/ywmpt/
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response...

Downloading multistrain data from https://osf.io/ywmpt/download

302 Found
Location: https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682cae3abb3f815770b06cc8 [following]
--2026-09-20 02:10:33--  https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682cae3abb3f815770b06cc8
Resolving files.osf.io (files.osf.io)... 35.186.214.196
Connecting to files.osf.io (files.osf.io)|35.186.214.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-us-east1/b6c38b1982ac61dc8727c85a0d9202e70b0b6f96a8465ecc658c156a647fc1dc?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-multistrain-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-multistrain-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870294&Signature=KsTRaJ1H5RRlqVuENrNVS%2B4BR4%2Bd5oVkNXWxfJZXNzLbV%2B5TqZDpV2UcPZxdmONRdRC32hXKWD1e0MmfJju3kZeLkX63LvgrEDU8nZdI17x6P70OgyJQHjmOo3S%2F4fgxkyw6U%2FjqzjQRFxv7Xhf%2B3yldYNA5grhtOBrIGVNX1nzKyY4jE4nd7zkOwK0%2B3WrEDh%2B6G1Xng2jnqcJh0bHKxKxkIAFtQZfY%2FE%2FvAr3UKaH3pnKyvmc7YuD3GYMpQDk7nvOmI8vw%2BDztiKoc3SpYatAcZe2Irc4U8m3wuXOWYGBDPNoAO9Va6ySQwyJo7FVWToIkIICYXXvuGfbLyD1YTw%3D%3D [following]
--2026-09-20 02:10:34--  https://storage.googleapis.com/cos-osf-prod-files-us-east1/b6c38b1982ac61dc8727c85a0d9202e70b0b6f96a8465ecc658c156a647fc1dc?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-multistrain-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-multistrain-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870294&Signature=KsTRaJ1H5RRlqVuENrNVS%2B4BR4%2Bd5oVkNXWxfJZXNzLbV%2B5TqZDpV2UcPZxdmONRdRC32hXKWD1e0MmfJju3kZeLkX63LvgrEDU8nZdI17x6P70OgyJQHjmOo3S%2F4fgxkyw6U%2FjqzjQRFxv7Xhf%2B3yldYNA5grhtOBrIGVNX1nzKyY4jE4nd7zkOwK0%2B3WrEDh%2B6G1Xng2jnqcJh0bHKxKxkIAFtQZfY%2FE%2FvAr3UKaH3pnKyvmc7YuD3GYMpQDk7nvOmI8vw%2BDztiKoc3SpYatAcZe2Irc4U8m3wuXOWYGBDPNoAO9Va6ySQwyJo7FVWToIkIICYXXvuGfbLyD1YTw%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 142.250.31.207, 142.251.179.207, 172.253.63.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|142.250.31.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1164969026 (1.1G) [application/octet-stream]
Saving to: ‘/tmp/2025-05-30-compscreen-mutcount.pqt’

/tmp/2025-05-30-com 100%[===================>]   1.08G   173MB/s    in 7.1s

2026-09-20 02:10:42 (155 MB/s) - ‘/tmp/2025-05-30-compscreen-mutcount.pqt’ saved [1164969026/1164969026]

done!

100%|██████████| 34/34 [01:08<00:00,  2.01s/it]
--2026-09-20 02:11:52--  https://osf.io/r8skg/download

Downloading vanilla data from https://osf.io/r8skg/download

Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osf.io/download/r8skg [following]
--2026-09-20 02:11:52--  https://osf.io/download/r8skg
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 308 Permanent Redirect
Location: https://osf.io/download/r8skg/ [following]
--2026-09-20 02:11:52--  https://osf.io/download/r8skg/
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 302 Found
Location: https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682ca9f0110faab595b06ed7 [following]
--2026-09-20 02:11:52--  https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682ca9f0110faab595b06ed7
Resolving files.osf.io (files.osf.io)... 35.186.214.196
Connecting to files.osf.io (files.osf.io)|35.186.214.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-us-east1/788ef61866d0af0e050affecd10025622a41162e5ea6eaee8880ae0dfdec0377?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-vanilla-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-vanilla-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870373&Signature=M%2FfzMKRtyBuhHXtG41fL5wJjefneb9C9c1%2FvdT8Q9rnL%2BlTHp4eC2LXX3Zuv5LOfC9UIbfmrgKvVzCwy%2Bcgq%2B5kPmedDtH3nR%2FNrDsLFpj2YQC7r8D8sxysjTHdCy4Gl2EIKxKAxDWZE%2Bo%2Fwx0PfaATlmVwZDc7YzmM43VXiKMROLDn7NunErOYJgsGQw1MXwZlBtRKBr%2FTw21KfQRbl6kGw4r0R6lgGmghXFTo6%2BytRa4Ij%2FnPteunfqzPqbaXyKPO26Ezfr%2Fn2ODD9MKGiYYSUwRZ0DU7%2BzU8fGUu0zRQJbS6G8N4qcJrkcKDQEOh7zYJJKUo40ak6cVSzhvm2%2FQ%3D%3D [following]
--2026-09-20 02:11:53--  https://storage.googleapis.com/cos-osf-prod-files-us-east1/788ef61866d0af0e050affecd10025622a41162e5ea6eaee8880ae0dfdec0377?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-17-vanilla-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-17-vanilla-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870373&Signature=M%2FfzMKRtyBuhHXtG41fL5wJjefneb9C9c1%2FvdT8Q9rnL%2BlTHp4eC2LXX3Zuv5LOfC9UIbfmrgKvVzCwy%2Bcgq%2B5kPmedDtH3nR%2FNrDsLFpj2YQC7r8D8sxysjTHdCy4Gl2EIKxKAxDWZE%2Bo%2Fwx0PfaATlmVwZDc7YzmM43VXiKMROLDn7NunErOYJgsGQw1MXwZlBtRKBr%2FTw21KfQRbl6kGw4r0R6lgGmghXFTo6%2BytRa4Ij%2FnPteunfqzPqbaXyKPO26Ezfr%2Fn2ODD9MKGiYYSUwRZ0DU7%2BzU8fGUu0zRQJbS6G8N4qcJrkcKDQEOh7zYJJKUo40ak6cVSzhvm2%2FQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 34.3.1.27, 34.144.170.27, 34.144.171.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.3.1.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 601842150 (574M) [application/octet-stream]
Saving to: ‘/tmp/2025-05-30-compscreen-mutcount.pqt’

/tmp/2025-05-30-com 100%[===================>] 573.96M   202MB/s    in 2.8s

2026-09-20 02:11:56 (202 MB/s) - ‘/tmp/2025-05-30-compscreen-mutcount.pqt’ saved [601842150/601842150]

done!

100%|██████████| 35/35 [00:51<00:00,  1.48s/it]
--2026-09-20 02:12:50--  https://osf.io/j4795/download
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osf.io/download/j4795 [following]
--2026-09-20 02:12:50--  https://osf.io/download/j4795
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 308 Permanent Redirect
Location: https://osf.io/download/j4795/ [following]
--2026-09-20 02:12:50--  https://osf.io/download/j4795/
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response...

Downloading vanilla-big data from https://osf.io/j4795/download

302 Found
Location: https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682cacb1bb3f815770b06ca1 [following]
--2026-09-20 02:12:50--  https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682cacb1bb3f815770b06ca1
Resolving files.osf.io (files.osf.io)... 35.186.214.196
Connecting to files.osf.io (files.osf.io)|35.186.214.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-us-east1/b576f902dbe245ec70c8b25de01163fe0bb924cc4eca461b0dfb4249d1babbd5?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-18-vanilla-big-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-18-vanilla-big-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870430&Signature=b2xXe7WRwsd0uy7YsxZlqFx7mpNhe1f61rr3T5Fw6ZpgiaZ1TClCw3izdRaxJudOi%2FYs8QDoJbOCjQBS0L3rupMJi4o0O499n8oWn0yBuvWc00Stp86NrKsElEYoI1gnGFCoaF3zgxXMOcwoBv4x2sNYvXmuQgd%2Bheap744XjN71Q8fnsm1s5idtrk5o3YpasrMmXRFlZCjMGJ53I7CnKa9%2F7W5R8nnubYG6USqZ6%2BJhb9Gw7q%2BzmJhPbNDYjG%2FjuTFtv65Ro42PZGGIioTB28OefVuR9GQxT6OfPrOw0NTkC6hYrWZ5L3hWJ8nWmhKHeAeZWc2U3vyNVt4w0d%2FwSA%3D%3D [following]
--2026-09-20 02:12:50--  https://storage.googleapis.com/cos-osf-prod-files-us-east1/b576f902dbe245ec70c8b25de01163fe0bb924cc4eca461b0dfb4249d1babbd5?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-18-vanilla-big-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-18-vanilla-big-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870430&Signature=b2xXe7WRwsd0uy7YsxZlqFx7mpNhe1f61rr3T5Fw6ZpgiaZ1TClCw3izdRaxJudOi%2FYs8QDoJbOCjQBS0L3rupMJi4o0O499n8oWn0yBuvWc00Stp86NrKsElEYoI1gnGFCoaF3zgxXMOcwoBv4x2sNYvXmuQgd%2Bheap744XjN71Q8fnsm1s5idtrk5o3YpasrMmXRFlZCjMGJ53I7CnKa9%2F7W5R8nnubYG6USqZ6%2BJhb9Gw7q%2BzmJhPbNDYjG%2FjuTFtv65Ro42PZGGIioTB28OefVuR9GQxT6OfPrOw0NTkC6hYrWZ5L3hWJ8nWmhKHeAeZWc2U3vyNVt4w0d%2FwSA%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 34.144.170.27, 34.3.1.27, 104.154.124.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.144.170.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 438162290 (418M) [application/octet-stream]
Saving to: ‘/tmp/2025-05-30-compscreen-mutcount.pqt’

/tmp/2025-05-30-com 100%[===================>] 417.86M  22.2MB/s    in 15s

2026-09-20 02:13:06 (27.9 MB/s) - ‘/tmp/2025-05-30-compscreen-mutcount.pqt’ saved [438162290/438162290]

done!

100%|██████████| 18/18 [00:14<00:00,  1.28it/s]
--2026-09-20 02:13:20--  https://osf.io/cnp5z/download
Resolving osf.io (osf.io)... 35.190.84.173
Connecting to osf.io (osf.io)|35.190.84.173|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://osf.io/download/cnp5z [following]
--2026-09-20 02:13:20--  https://osf.io/download/cnp5z
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response...

Downloading vanilla-big-1.3x data from https://osf.io/cnp5z/download

308 Permanent Redirect
Location: https://osf.io/download/cnp5z/ [following]
--2026-09-20 02:13:20--  https://osf.io/download/cnp5z/
Reusing existing connection to osf.io:443.
HTTP request sent, awaiting response... 302 Found
Location: https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682caa9fbb3f815770b06c6b [following]
--2026-09-20 02:13:20--  https://files.osf.io/v1/resources/37fv8/providers/osfstorage/682caa9fbb3f815770b06c6b
Resolving files.osf.io (files.osf.io)... 35.186.214.196
Connecting to files.osf.io (files.osf.io)|35.186.214.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://storage.googleapis.com/cos-osf-prod-files-us-east1/2699685afb8432314e32aeb42461c6e793a5657919f106fac95e2c3836dcd309?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-18-vanilla-big-1-3x-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-18-vanilla-big-1-3x-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870461&Signature=Sxm0QvN98nSjbREEjEmQJzf20IjI0KSxX9GvyPemLSu%2BtSpEmajI3SxobHbgMzp685BToOzCAP5uPgauAL%2FS6mEiGBLRtDoyHo1aYszX3UoVd%2Fc54FAoFh7KS9tHRZB8rkdB5DVQIahU0lz3P6LSS762X%2ByglCbH0ptPFx6XGL741SnlWm3dgNu186%2BOhJxxM1nGwD%2BbSNybJZHy2JNSGyJJpFl2qMFz9YTmnjaKPEcFqBX5f97RDHqY0Yml1jtcvt3Wbf19VRZPWZyuAdBqNFXbRMLZEQOMQxSdWMw8o%2B7Ibfdl5RUDEZ9Mcb7I0VV6OAp3XzNuL%2FXm6rtc%2F2LITQ%3D%3D [following]
--2026-09-20 02:13:21--  https://storage.googleapis.com/cos-osf-prod-files-us-east1/2699685afb8432314e32aeb42461c6e793a5657919f106fac95e2c3836dcd309?response-content-disposition=attachment%3B%20filename%3D%22a%3Dresult%2Bdate%3D2025-05-20%2Bjob%3D2025-05-18-vanilla-big-1-3x-run_compscreen%2Bext%3D.pqt%22%3B%20filename%2A%3DUTF-8%27%27a%253Dresult%252Bdate%253D2025-05-20%252Bjob%253D2025-05-18-vanilla-big-1-3x-run_compscreen%252Bext%253D.pqt&GoogleAccessId=files-us%40cos-osf-prod.iam.gserviceaccount.com&Expires=1789870461&Signature=Sxm0QvN98nSjbREEjEmQJzf20IjI0KSxX9GvyPemLSu%2BtSpEmajI3SxobHbgMzp685BToOzCAP5uPgauAL%2FS6mEiGBLRtDoyHo1aYszX3UoVd%2Fc54FAoFh7KS9tHRZB8rkdB5DVQIahU0lz3P6LSS762X%2ByglCbH0ptPFx6XGL741SnlWm3dgNu186%2BOhJxxM1nGwD%2BbSNybJZHy2JNSGyJJpFl2qMFz9YTmnjaKPEcFqBX5f97RDHqY0Yml1jtcvt3Wbf19VRZPWZyuAdBqNFXbRMLZEQOMQxSdWMw8o%2B7Ibfdl5RUDEZ9Mcb7I0VV6OAp3XzNuL%2FXm6rtc%2F2LITQ%3D%3D
Resolving storage.googleapis.com (storage.googleapis.com)... 34.153.2.27, 34.3.0.27, 104.154.124.27, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|34.153.2.27|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 801307036 (764M) [application/octet-stream]
Saving to: ‘/tmp/2025-05-30-compscreen-mutcount.pqt’

/tmp/2025-05-30-com 100%[===================>] 764.19M   163MB/s    in 5.2s

2026-09-20 02:13:27 (146 MB/s) - ‘/tmp/2025-05-30-compscreen-mutcount.pqt’ saved [801307036/801307036]

done!

100%|██████████| 20/20 [00:22<00:00,  1.11s/it]

In [9]:
results_df = pd.DataFrame(results)
results_df.to_csv(
    f"{teeplot_subdir}-raw.csv",
    index=False,
)
results_df

,source_name,trt_name,trt_n_downsample,trt_hsurf_bits,replicate_uuid,sum leaf count,sum defmut
0,uk,Sben2x/Gdel2x,1000000,0,0f07d386-bc29-8b1c-9c27-adc93df6f99f,522,274
1,uk,Sben1.1x/Gneu,1000000,64,1295ccfb-605c-88c9-8ebf-900370e800d0,1,1
2,uk,Sben2x/Gneu,1000000,0,29143eaa-000f-832e-95e4-edb14e6958b1,9508,600
3,uk,Sben2x/Gneu,1000000,64,29143eaa-000f-832e-95e4-edb14e6958b1,398,398
4,uk,Sben1.3x/Gdel1.3x,1000000,64,6cca2f5d-7303-80aa-9b56-c65a26f04eba,9,9
...,...,...,...,...,...,...,...
172,vanilla-big-1.3x,Sben1.3x/Gdel1.3x,200000,0,c81cab91-5dfe-83d3-a088-110240579728,420,237
173,vanilla-big-1.3x,Sben1.3x/Gdel1.3x,2000000,0,2b2da60e-53a7-8888-9058-ce1b89fb83e3,4805,1298
174,vanilla-big-1.3x,Sben1.3x/Gdel1.3x,200000,0,15f36e76-1fe6-861d-bf0c-b171c07713df,371,242
175,vanilla-big-1.3x,Sben1.3x/Gdel1.3x,200000,0,2b2da60e-53a7-8888-9058-ce1b89fb83e3,485,272
176,vanilla-big-1.3x,Sben1.3x/Gneu,200000,0,a2dd9970-e3a6-8941-b6d4-45b9c54ac506,6218,499

In [10]:
summary_df = results_df.groupby(
    ["source_name", "trt_name", "trt_n_downsample", "trt_hsurf_bits"]
).agg(
    {
        "sum leaf count": ["mean", "std"],
        "sum defmut": ["mean", "std"],
    },
)
summary_df.to_csv(
    f"{teeplot_subdir}-summary.csv",
    index=True,
)
summary_df

                                                                   sum leaf count  \
                                                                             mean
source_name      trt_name          trt_n_downsample trt_hsurf_bits
multistrain      Sben1.1x/Gdel1.1x 1000000          0                       865.8
                 Sben1.1x/Gneu     1000000          0                       323.4
                 Sben1.3x/Gdel1.3x 1000000          0                     1,543.8
                 Sben1.3x/Gneu     1000000          0                     6,386.8
                 Sben2x/Gdel2x     1000000          0                    12,510.8
                 Sben2x/Gneu       1000000          0                   105,072.2
                 Sneu/Gneu         1000000          0                        92.0
uk               Sben1.1x/Gdel1.1x 1000000          0                         1.6
                                                    64                        1.2
                 Sben1.1x/Gneu     1000000          0                         3.2
                                                    64                        1.0
                 Sben1.3x/Gdel1.3x 1000000          0                        67.8
                                                    64                        9.0
                 Sben1.3x/Gneu     1000000          0                       130.0
                                                    64                       10.4
                 Sben2x/Gdel2x     1000000          0                       559.2
                                                    64                      210.2
                 Sben2x/Gneu       1000000          0                     6,436.6
                                                    64                      348.6
                 Sneu/Gneu         1000000          0                         1.2
                                                    64                        0.6
vanilla          Sben1.1x/Gdel1.1x 1000000          0                       141.2
                 Sben1.1x/Gneu     1000000          0                       525.0
                 Sben1.3x/Gdel1.3x 1000000          0                     6,154.4
                 Sben1.3x/Gneu     1000000          0                    29,039.6
                 Sben2x/Gdel2x     1000000          0                    18,099.4
                 Sben2x/Gneu       1000000          0                   299,979.0
                 Sneu/Gneu         1000000          0                        85.0
vanilla-big      Sben1.1x/Gdel1.1x 200000           0                       201.0
                                                    64                       12.7
                                   2000000          0                     2,684.7
                 Sben1.1x/Gneu     200000           0                       356.0
                                                    64                       30.0
                                   2000000          0                     4,005.7
vanilla-big-1.3x Sben1.3x/Gdel1.3x 200000           0                       409.2
                                   2000000          0                     4,892.6
                 Sben1.3x/Gneu     200000           0                     5,819.0
                                   2000000          0                    58,494.4

                                                                             \
                                                                        std
source_name      trt_name          trt_n_downsample trt_hsurf_bits
multistrain      Sben1.1x/Gdel1.1x 1000000          0                 438.4
                 Sben1.1x/Gneu     1000000          0                 241.1
                 Sben1.3x/Gdel1.3x 1000000          0                 380.3
                 Sben1.3x/Gneu     1000000          0               2,054.2
                 Sben2x/Gdel2x     1000000          0               1,560.2
                 Sben2x/Gneu       1000000          0               1,953.9
                 Sneu/Gneu         1000000          0                  92.4
uk               Sben1.1x/Gdel1.1x 1000000          0                   1.3
                                                    64                  1.1
                 Sben1.1x/Gneu     1000000          0                   3.6
                                                    64                  0.7
                 Sben1.3x/Gdel1.3x 1000000          0                  21.4
                                                    64                  2.5
                 Sben1.3x/Gneu     1000000          0                 168.2
                                                    64                  5.1
                 Sben2x/Gdel2x     1000000          0                  84.0
                                                    64                 15.9
                 Sben2x/Gneu       1000000          0               4,531.0
                                                    64                 47.7
                 Sneu/Gneu         1000000          0                   1.6
                                                    64                  1.3
vanilla          Sben1.1x/Gdel1.1x 1000000          0                 103.7
                 Sben1.1x/Gneu     1000000          0                 478.8
                 Sben1.3x/Gdel1.3x 1000000          0               9,340.5
                 Sben1.3x/Gneu     1000000          0              10,707.9
                 Sben2x/Gdel2x     1000000          0               6,142.3
                 Sben2x/Gneu       1000000          0              19,759.4
                 Sneu/Gneu         1000000          0                  80.7
vanilla-big      Sben1.1x/Gdel1.1x 200000           0                 167.0
                                                    64                  3.1
                                   2000000          0               2,453.3
                 Sben1.1x/Gneu     200000           0                 391.6
                                                    64                 27.6
                                   2000000          0               3,699.2
vanilla-big-1.3x Sben1.3x/Gdel1.3x 200000           0                  51.6
                                   2000000          0               1,014.8
                 Sben1.3x/Gneu     200000           0               1,354.7
                                   2000000          0              13,840.2

                                                                   sum defmut  \
                                                                         mean
source_name      trt_name          trt_n_downsample trt_hsurf_bits
multistrain      Sben1.1x/Gdel1.1x 1000000          0                    25.5
                 Sben1.1x/Gneu     1000000          0                    29.4
                 Sben1.3x/Gdel1.3x 1000000          0                   297.2
                 Sben1.3x/Gneu     1000000          0                   423.0
                 Sben2x/Gdel2x     1000000          0                 5,630.4
                 Sben2x/Gneu       1000000          0                 9,488.4
                 Sneu/Gneu         1000000          0                    16.6
uk               Sben1.1x/Gdel1.1x 1000000          0                     1.4
                                                    64                    1.2
                 Sben1.1x/Gneu     1000000          0                     1.2
                                                    64                    1.0
                 Sben1.3x/Gdel1.3x 1000000          0                    13.8
                                                    64                    9.0
                 Sben1.3x/Gneu     1000000          0                    13.4
                                                    64                   10.4
                 Sben2x/Gdel2x     1000000          0                   275.2
                                                    64                  210.2
                 Sben2x/Gneu       1000000          0                   510.0
                                                    64                  348.6
                 Sneu/Gneu         1000000          0                     1.0
                                                    64                    0.6
vanilla          Sben1.1x/Gdel1.1x 1000000          0                    18.4
                 Sben1.1x/Gneu     1000000          0                    21.2
                 Sben1.3x/Gdel1.3x 1000000          0                   361.4
                 Sben1.3x/Gneu     1000000          0                   465.6
                 Sben2x/Gdel2x     1000000          0                 6,679.0
                 Sben2x/Gneu       1000000          0                 8,493.2
                 Sneu/Gneu         1000000          0                    14.8
vanilla-big      Sben1.1x/Gdel1.1x 200000           0                    17.3
                                                    64                   12.7
                                   2000000          0                    64.7
                 Sben1.1x/Gneu     200000           0                    18.3
                                                    64                   30.0
                                   2000000          0                    67.7
vanilla-big-1.3x Sben1.3x/Gdel1.3x 200000           0                   248.8
                                   2000000          0                 1,292.0
                 Sben1.3x/Gneu     200000           0                   484.0
                                   2000000          0                 1,758.8


                                                                     std
source_name      trt_name          trt_n_downsample trt_hsurf_bits
multistrain      Sben1.1x/Gdel1.1x 1000000          0                1.3
                 Sben1.1x/Gneu     1000000          0               10.1
                 Sben1.3x/Gdel1.3x 1000000          0               26.4
                 Sben1.3x/Gneu     1000000          0               34.3
                 Sben2x/Gdel2x     1000000          0               48.7
                 Sben2x/Gneu       1000000          0               83.1
                 Sneu/Gneu         1000000          0                3.6
uk               Sben1.1x/Gdel1.1x 1000000          0                1.1
                                                    64               1.1
                 Sben1.1x/Gneu     1000000          0                0.8
                                                    64               0.7
                 Sben1.3x/Gdel1.3x 1000000          0                4.4
                                                    64               2.5
                 Sben1.3x/Gneu     1000000          0                4.4
                                                    64               5.1
                 Sben2x/Gdel2x     1000000          0               19.4
                                                    64              15.9
                 Sben2x/Gneu       1000000          0               62.1
                                                    64              47.7
                 Sneu/Gneu         1000000          0                1.4
                                                    64               1.3
vanilla          Sben1.1x/Gdel1.1x 1000000          0                4.2
                 Sben1.1x/Gneu     1000000          0                5.6
                 Sben1.3x/Gdel1.3x 1000000          0               37.2
                 Sben1.3x/Gneu     1000000          0               41.7
                 Sben2x/Gdel2x     1000000          0               82.2
                 Sben2x/Gneu       1000000          0              284.5
                 Sneu/Gneu         1000000          0                1.6
vanilla-big      Sben1.1x/Gdel1.1x 200000           0                2.3
                                                    64               3.1
                                   2000000          0                6.7
                 Sben1.1x/Gneu     200000           0                4.5
                                                    64              27.6
                                   2000000          0               10.7
vanilla-big-1.3x Sben1.3x/Gdel1.3x 200000           0               15.8
                                   2000000          0               23.7
                 Sben1.3x/Gneu     200000           0               36.0
                                   2000000          0               59.2